# Generated by Django 3.2 on 2023-01-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20230103_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='purchase',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('business', 'ビジネス'), ('life', '生活'), ('entartainment', '娯楽'), ('other', 'その他')], max_length=100),
        ),
    ]
